version: "3.6"
services:
  postgres:
    image: postgres:14-alpine
    container_name: develop.webhook.postgres
    command: postgres -c max_connections=200
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      ENV: ${ENV:-develop}
    volumes:
      - ./utils/postgresql/data:/var/lib/postgresql/data
      - ./utils/postgresql/init:/docker-entrypoint-initdb.d
    ports:
      - 54321:5432
  
  redis:
    image: "redis:alpine"
    container_name: develop.redis
    ports:
      - "6379:6379"

  worker:
    container_name: develop.webhook.worker
    build:
      context: ./app/tasks
      dockerfile: Dockerfile
    command: celery -A task.upload_file.celery worker --loglevel=info
    environment:
      CELERY_BROKER_URL: redis://develop.redis:6379/0
      CELERY_RESULT_BACKEND: redis://develop.redis:6379/0
      DATABASE_URL: postgresql://root:secret@develop.webhook.postgres:5434/webhook?sslmode=disable
    depends_on:
      - redis
      - api
    volumes:
      - './app/tasks:/worker'
  
  celery-monitor:
    container_name: develop.webhook.celery-monitor
    build:
      context: ./app/tasks
      dockerfile: Dockerfile 
    ports:
      - "5555:5555"
    command: ['celery','--broker','redis://127.0.0.1:6379/0','flower','-A','tasks']
    environment:
      CELERY_BROKER_URL: redis://develop.redis:6379/0
      CELERY_RESULT_BACKEND: redis://develop.redis:6379/0
      DATABASE_URL: postgresql://root:secret@develop.webhook.postgres:5434/webhook?sslmode=disable
    depends_on:
      - redis
      - worker
    volumes:
      - './app/tasks:/worker'

  api:
    container_name: develop.webhook.api
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      CELERY_BROKER_URL: redis://develop.redis:6379/0
      CELERY_RESULT_BACKEND: redis://develop.redis:6379/0
      DATABASE_URL: postgresql://root:secret@develop.webhook.postgres:5434/webhook?sslmode=disable
    depends_on:
      - redis
    volumes:
      - './app:/api'