version: "3.6"
services:
  postgres:
    image: postgres:14-alpine
    container_name: develop.webhook.postgres
    command: postgres -c max_connections=200
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      ENV: ${ENV:-develop}
    volumes:
      - ./utils/postgresql/data:/var/lib/postgresql/data
      - ./utils/postgresql/init:/docker-entrypoint-initdb.d
    ports:
      - 54321:5432
  
  redis:
    image: "redis:alpine"
    container_name: develop.redis
    ports:
      - "6379:6379"

  worker:
    build:
      context: ./celery-queue
      dockerfile: Dockerfile
    command: celery -A tasks worker -l info -E
    environment:
      CELERY_BROKER_URL: redis://develop.redis:6379/0
      CELERY_RESULT_BACKEND: redis://develop.redis:6379/0
    depends_on:
      - redis
    volumes: ['./app/tasks:/queue']
  
  celery-monitor:
    build:
      context: ./app/task
      dockerfile: Dockerfile 
    ports:
    - "5555:5555"
    command: ['celery','flower','-A','tasks']
    environment:
      CELERY_BROKER_URL: redis://develop.redis:6379/0
      CELERY_RESULT_BACKEND: redis://develop.redis:6379/0
    depends_on:
      - redis
      - worker