CREATE TABLE webhook_registrations (
    id  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL,
    url VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP 
);

CREATE TABLE event_types (
    id  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description TEXT
);

CREATE TABLE webhook_configurations (
    id  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    webhook_id INT NOT NULL,
    event_type_id INT NOT NULL,
    custom_headers JSON,  
    custom_payload JSON, 
    FOREIGN KEY (webhook_id) REFERENCES webhook_registrations(id),
    FOREIGN KEY (event_type_id) REFERENCES event_types(id)
);

CREATE TABLE error_log (
    id  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    webhook_execution_id INT NOT NULL,
    error_message TEXT NOT NULL,
    retry_count INT DEFAULT 0,
    next_retry_time TIMESTAMP
);